version: "3"
services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: kartographer
      MONGO_INITDB_ROOT_PASSWORD: kartographer
  kartographer:
    build: .
    restart: always
    ports: ["8080:8080"]
    environment:
      MONGODB_URI: mongodb://kartographer:kartographer@db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://kartographer:kartographer@db
